#C_DEFS += -DPRINTF_FLOAT
#C_DEFS += -DUSE_PWM
C_DEFS += -DUSE_UART
C_DEFS += -DUSE_SPI
#C_DEFS += -DUSE_ADC
#C_DEFS += -DUSE_TIMER
#C_DEFS += -DUSE_CAN
#C_DEFS += -DUSE_USB
C_DEFS += -DUSE_SPI23S17

